# Generated by Django 5.2.5 on 2026-01-05 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_post_likes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
