# Generated by Django 5.2.5 on 2026-01-05 12:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_post_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.IntegerField(unique=True),
                blank=True,
                default=list,
                size=None,
            ),
        ),
    ]
