# Generated by Django 5.2.5 on 2026-01-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_alter_post_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.IntegerField()),
                ("user_id", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="post",
            name="likes",
            field=models.IntegerField(default=0),
        ),
    ]
