# Generated by Django 5.2.5 on 2026-01-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_like_alter_post_likes"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.CharField(default="", max_length=120),
        ),
    ]
