# Generated by Django 5.2.5 on 2026-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(default="", upload_to=""),
        ),
    ]
