# Generated by Django 5.2.5 on 2026-01-09 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
    ]
