# Generated by Django 5.2.5 on 2026-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_remove_user_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.CharField(default=""),
        ),
    ]
