# Generated by Django 5.2.5 on 2026-01-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_user_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.CharField(blank=True, default=""),
        ),
    ]
