# Generated by Django 5.2.5 on 2026-01-13 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_alter_user_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="likes",
        ),
    ]
